name: NearX
version: '${project.version}'
main: com.deathspirit.nearx.NearX
api-version: 1.16
authors: [ SpiritDev ]
description: Лучший /near для вашего сервера
depend:
  - "Essentials"
commands:
  nearx:
